<?xml version="1.0" encoding="ISO-8859-1"?>
<!--This file was created automatically by xsl2profile-->
<!--from the DocBook XSL stylesheets. Do not edit this file.-->
<xsl:stylesheet xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:exsl="http://exslt.org/common" xmlns:fo="http://www.w3.org/1999/XSL/Format" xmlns:ng="http://docbook.org/docbook-ng" xmlns:db="http://docbook.org/ns/docbook" xmlns:exslt="http://exslt.org/common" exslt:dummy="dummy" extension-element-prefixes="exslt" exclude-result-prefixes="db ng exsl exslt" version="1.0">

<xsl:import href="profile-docbook.xsl"/>

<!-- It is important to use indent="no" here, otherwise verbatim -->
<!-- environments get broken by indented tags...at least when the -->
<!-- callout extension is used...at least with some processors -->
<xsl:output method="xml" indent="no"/>

<!-- Génération de la table des matières -->
<xsl:param name="generate.toc" select="'book toc'"/>

<!-- Changement de la typo du texte -->
<xsl:param name="body.font.family">Palatino</xsl:param>
<xsl:param name="body.font.master">11</xsl:param>
<xsl:param name="releaseinfo.font.size">4</xsl:param>
<!-- <xsl:param name="body.start.indent">24pt</xsl:param> -->

<!-- Numérotation des chapitres -->
<xsl:param name="title.font.family">Helvetica</xsl:param>
<xsl:param name="section.autolabel">1</xsl:param>
<xsl:param name="section.autolabel.max.depth">3</xsl:param>

<!-- Marges et mise en page 
<xsl:param name="page.margin.bottom" select="'0.8cm'"/>
<xsl:param name="page.margin.top" select="'0.8cm'"/> -->
<xsl:param name="page.margin.inner" select="'1cm'"/>
<xsl:param name="page.margin.outer" select="'1cm'"/>


<!-- Calage des marges des titres au même niveau que le 
reste du texte, résoud un bug si fop.extensions=1 -->
<xsl:param name="title.margin.left" select="'0cm'"/>
<xsl:param name="title.margin.right" select="'0cm'"/>

<!-- Titres de section 1 -->
<xsl:attribute-set name="chapter.title.properties">
<!--  <xsl:attribute name="break-before">page</xsl:attribute> -->
  <xsl:attribute name="font-size">80pt</xsl:attribute>
  <xsl:attribute name="padding-top">6pt</xsl:attribute>
  <xsl:attribute name="padding-bottom">3pt</xsl:attribute>
   <!-- xsl:attribute name="break-before">page</xsl:attribute -->
  <!-- <xsl:attribute name="background-color">#D5D5F0</xsl:attribute> -->
  <xsl:attribute name="border-bottom">0.2pt solid #C5C5C5</xsl:attribute>     
</xsl:attribute-set> 

<!-- Titres de section 1 -->
<xsl:attribute-set name="section.title.level1.properties">
<!--  <xsl:attribute name="break-before">page</xsl:attribute> -->
  <xsl:attribute name="font-size">15pt</xsl:attribute>
  <xsl:attribute name="padding-top">6pt</xsl:attribute>
  <xsl:attribute name="padding-bottom">3pt</xsl:attribute>
   <!-- xsl:attribute name="break-before">page</xsl:attribute -->
  <!-- <xsl:attribute name="background-color">#D5D5F0</xsl:attribute> -->
  <xsl:attribute name="border-bottom">0.2pt solid #C5C5C5</xsl:attribute>     
</xsl:attribute-set> 

<!-- Titres de section 2 -->
<xsl:attribute-set name="section.title.level2.properties">
   <!-- xsl:attribute name="break-before">page</xsl:attribute -->
  <xsl:attribute name="font-size">13pt</xsl:attribute>
  <xsl:attribute name="border-bottom">0.2pt solid #C5C5C5</xsl:attribute>     
</xsl:attribute-set> 

<!-- Titres de section 3 -->
<xsl:attribute-set name="section.title.level3.properties">
  <xsl:attribute name="font-size">11pt</xsl:attribute>
   <!-- xsl:attribute name="break-before">page</xsl:attribute -->
  <xsl:attribute name="border-bottom">0.2pt solid #C5C5C5</xsl:attribute>     
</xsl:attribute-set> 

<!-- Titres de section 4 -->
<xsl:attribute-set name="section.title.level4.properties">
   <!-- xsl:attribute name="break-before">page</xsl:attribute -->
  <xsl:attribute name="text-decoration">underline</xsl:attribute>
</xsl:attribute-set> 


<!-- Titres des figures et tableaux -->
<xsl:attribute-set name="formal.title.properties">
  <xsl:attribute name="margin-top">2pt</xsl:attribute>
  <xsl:attribute name="font-size">8pt</xsl:attribute> 
  <xsl:attribute name="font-family">Helvetica</xsl:attribute>
</xsl:attribute-set>

<!-- Position des titres des figures et tableaux -->
<xsl:param name="formal.title.placement">
figure after
example before
equation before
table before
procedure before
</xsl:param>
<!-- Obligé de commenter : ça bugge !
-->

<!-- Suppression de la numérotation des captures et images -->
<xsl:param name="local.l10n.xml" select="document('')"/>
<l:i18n xmlns:l="http://docbook.sourceforge.net/xmlns/l10n/1.0">
<l:l10n xmlns:l="http://docbook.sourceforge.net/xmlns/l10n/1.0" language="fr" english-language-name="French">
   <l:context name="title">
      <l:template name="example" text="%t"/>
      <l:template name="figure" text="%t"/>
      <l:template name="table" text="%t"/>
   </l:context>
 </l:l10n>
</l:i18n>

<!-- Espacement des listes à puces -->
<xsl:attribute-set name="list.item.spacing">
  <xsl:attribute name="space-before.optimum">0.3em</xsl:attribute>
  <xsl:attribute name="space-before.minimum">0.1em</xsl:attribute>
  <xsl:attribute name="space-before.maximum">0.5em</xsl:attribute>
</xsl:attribute-set>

<!-- Espacement des paragraphes -->
<xsl:attribute-set name="normal.para.spacing">
  <xsl:attribute name="space-before.optimum">0.7em</xsl:attribute>
  <xsl:attribute name="space-before.minimum">0.6em</xsl:attribute>
  <xsl:attribute name="space-before.maximum">0.9em</xsl:attribute>
</xsl:attribute-set>

<!-- ajout d'un timestamp dans les infos du livre-->
<!-- <xsl:template name="book.bookinfo">
  <meta name="date">
    <xsl:attribute name="content">
      <xsl:call-template name="datetime.format">
        <xsl:with-param name="date" select="date:date-time()"/>
        <xsl:with-param name="format" select="'m/d/Y'"/>  
      </xsl:call-template>
    </xsl:attribute>
  </meta>
</xsl:template> -->

<!-- Changement de la taille du texte dans les tableaux --> 
<xsl:template name="table.cell.block.properties">
<!-- gras sur entete 
  <xsl:if test="ancestor::thead">
    <xsl:attribute name="font-weight">bold</xsl:attribute>
  </xsl:if>
-->
  <xsl:attribute name="font-size">
    <xsl:value-of select="$body.font.master * 0.7"/>
    <xsl:text>pt</xsl:text>
  </xsl:attribute>
</xsl:template>


<!-- lien colorés en bleus (grisés en noir et blanc), sans ajout de l'adresse entre crochets -->
    <xsl:template match="ulink">
        <fo:basic-link external-destination="{@url}"
                xsl:use-attribute-sets="xref.properties"
		text-decoration="underline"
                color="#000088">
            <xsl:choose>
                <xsl:when test="count(child::node())=0">
                    <xsl:value-of select="@url" />
                </xsl:when>
                <xsl:otherwise>
                    <xsl:apply-templates />
                </xsl:otherwise>
            </xsl:choose>
        </fo:basic-link>
    </xsl:template>

<!-- alignement des figure et légende au centre de la page -->
<xsl:attribute-set name="figure.properties">
<xsl:attribute name="text-align">center</xsl:attribute>
</xsl:attribute-set>

<!-- Hauteur du header -->
<xsl:param name="region.before.extent" select="'1in'"/><!-- Hauteur du header -->
<xsl:param name="region.after.extent" select="'1in'"/><!-- Taille de la police du pied de page. -->
<xsl:param name="footnote.font.size">10pt</xsl:param>

<!-- Bottom of footer area to bottom of page edge. -->
<xsl:param name="page.margin.bottom">0.5in</xsl:param>

<!-- Top of header area to top of main text area. -->
<xsl:param name="body.margin.top">0.5in</xsl:param>

<!-- Bottom of main text area to bottom of footer area. -->
<xsl:param name="body.margin.bottom">0.5in</xsl:param>

<!-- Header content and placement. -->
<xsl:template name="header.content">
<xsl:param name="pageclass" select="''"/>
<xsl:param name="sequence" select="''"/>
<xsl:param name="position" select="''"/>
<xsl:param name="gentext-key" select="''"/>
<xsl:variable name="candidate">
<!-- sequence can be odd, even, first, blank -->
<!-- position can be left, center, right -->
<xsl:choose>

<xsl:when test="$sequence = 'even' and $position = 'left'">
<fo:retrieve-marker
retrieve-class-name="section.head.marker" />
</xsl:when>

<xsl:when test="$sequence = 'odd' and $position = 'right'">
<xsl:apply-templates select="." mode="object.title.markup"/>
</xsl:when>

<xsl:when test="$sequence = 'blank' and $position = 'left'">
</xsl:when>
<xsl:when test="$sequence = 'blank' and $position = 'center'">
<!-- no output -->
</xsl:when>
<xsl:when test="$sequence = 'blank' and $position = 'right'">
</xsl:when>
</xsl:choose>
</xsl:variable>

<!-- Does runtime parameter turn off blank page headers? -->
<xsl:choose>
<xsl:when test="$sequence='blank' and $headers.on.blank.pages=1">
<!-- no output -->
</xsl:when>

<!-- titlepages have no headers -->
<xsl:when test="$pageclass = 'titlepage'">
<!-- no output -->
</xsl:when>
<xsl:otherwise>
<xsl:copy-of select="$candidate"/>
</xsl:otherwise>
</xsl:choose>
</xsl:template>

<!-- Header fonts and font size. -->
<xsl:attribute-set name="header.content.properties">
<!-- <xsl:attribute name="font-family">Your-Font</xsl:attribute> -->
<xsl:attribute name="font-size">8pt</xsl:attribute>
</xsl:attribute-set>

<!-- Header rule -->
<xsl:template name="head.sep.rule">
<xsl:param name="sequence" select="''"/>
<xsl:if test="$header.rule != 0 and $sequence != 'first' and $sequence !=
'blank'">
<xsl:attribute name="border-bottom-width">0.3pt</xsl:attribute>
<xsl:attribute name="border-bottom-style">solid</xsl:attribute>
<xsl:attribute name="border-bottom-color">#E0E0E0</xsl:attribute>
</xsl:if>
</xsl:template>

<!-- Footer content and placement. -->
<xsl:template name="footer.content">
<xsl:param name="pageclass" select="''"/>
<xsl:param name="sequence" select="''"/>
<xsl:param name="position" select="''"/>
<xsl:param name="gentext-key" select="''"/>
<xsl:variable name="candidate">
<!-- sequence can be odd, even, first, blank -->
<!-- position can be left, center, right -->
<xsl:choose>
<xsl:when test="$sequence = 'odd' and $position = 'left'">
</xsl:when>
<xsl:when test="$sequence = 'odd' and $position = 'center'">
</xsl:when>
<xsl:when test="$sequence = 'odd' and $position = 'right'">
<fo:page-number/>
</xsl:when>
<xsl:when test="$sequence = 'even' and $position = 'left'">
<fo:page-number/>
</xsl:when>
<xsl:when test="$sequence = 'even' and $position = 'center'">
</xsl:when>
<xsl:when test="$sequence = 'even' and $position = 'right'">
</xsl:when>
<xsl:when test="$sequence = 'first' and $position = 'left'">
</xsl:when>
<xsl:when test="$sequence = 'first' and $position = 'right'">
</xsl:when>
<xsl:when test="$sequence = 'first' and $position = 'center'">
</xsl:when>
<xsl:when test="$sequence = 'blank' and $position = 'left'">
</xsl:when>
<xsl:when test="$sequence = 'blank' and $position = 'center'">
</xsl:when>
<xsl:when test="$sequence = 'blank' and $position = 'right'">
</xsl:when>
</xsl:choose>
</xsl:variable>
<!-- Does runtime parameter turn off blank page footers? -->
<xsl:choose>
<xsl:when test="$sequence='blank' and $footers.on.blank.pages=0">
<!-- no output -->
</xsl:when>
<!-- titlepages have no footers -->
<xsl:when test="$pageclass = 'titlepage'">
<!-- no output -->
</xsl:when>
<xsl:otherwise>
<xsl:copy-of select="$candidate"/>
</xsl:otherwise>
</xsl:choose>
</xsl:template>


<!-- Footer fonts and font size. -->
<xsl:attribute-set name="footer.content.properties">
<xsl:attribute name="font-family">Palatino</xsl:attribute>
<xsl:attribute name="font-size">10pt</xsl:attribute>
</xsl:attribute-set>

<!-- Footer rule -->
<xsl:template name="foot.sep.rule">
<xsl:param name="sequence" select="''"/>
<xsl:if test="$footer.rule != 0 and $sequence != 'first' and $sequence !=
'blank'">
<!-- 15/02/2008 suppression du filet en bas de page pour alléger
<xsl:attribute name="border-top-width">0.3pt</xsl:attribute>
<xsl:attribute name="border-top-style">solid</xsl:attribute>
<xsl:attribute name="border-top-color">#E0E0E0</xsl:attribute>
-->
</xsl:if>
</xsl:template>

<xsl:param name="header.column.widths" select="'1 0 1'"></xsl:param>

<xsl:template match="title" mode="chapter.titlepage.recto.auto.mode">
<fo:block xsl:use-attribute-sets="chapter.titlepage.recto.style"
margin-top="0in" margin-bottom="0.25in" font-size="25pt">
<xsl:call-template name="component.title">
<xsl:with-param name="node" select="ancestor-or-self::chapter[1]"/>
</xsl:call-template>
</fo:block>
</xsl:template>

<!--
<xsl:template match="important">
<xsl:variable name="id">
<xsl:call-template name="object.id"/>
</xsl:variable>
<fo:block keep-together="always" space-before.minimum="0em" space-before.optimum="0.2em"
space-before.maximum="1.2em" border="4pt solid #d0d0d0" background-color="#d0d0d0" padding="4pt" id="{$id}">
<fo:block text-align="left">
<fo:external-graphic src="url(images/engrenages.jpg)" content-height="2em" vertical-align="bottom"/> Paramètres
<xsl:apply-templates/>
</fo:block>
</fo:block>
</xsl:template>
-->

<xsl:template match="important">
<xsl:variable name="id">
<xsl:call-template name="object.id"/>
</xsl:variable>
<fo:table border-collapse="collapse" border="4pt solid #d0d0d0" background-color="#d0d0d0" padding="4pt" margin-top="10pt">
    <fo:table-column column-width="16%"/>
    <fo:table-column column-width="84%"/>
    <fo:table-body>
        <fo:table-row>
            <fo:table-cell text-align="start" overflow="hidden">
                <fo:block><fo:external-graphic src="url(images/engrenages.jpg)" content-height="4em"/></fo:block>
            </fo:table-cell>
            <fo:table-cell text-align="start">
                <fo:block><xsl:apply-templates/></fo:block>
            </fo:table-cell>
        </fo:table-row>
    </fo:table-body>
</fo:table>
</xsl:template>

<xsl:template name="book.titlepage.recto">
  <fo:block>
    <fo:table inline-progression-dimension="100%" table-layout="fixed">
      <fo:table-column column-width="50%"/>
      <fo:table-column column-width="50%"/>
      <fo:table-body>
        <fo:table-row >
          <fo:table-cell number-columns-spanned="2">
            <fo:block text-align="center">
              <xsl:choose>
                <xsl:when test="bookinfo/title">
                  <xsl:apply-templates 
                         mode="book.titlepage.recto.auto.mode" 
                         select="bookinfo/title"/>
                </xsl:when>
                <xsl:when test="title">
                  <xsl:apply-templates 
                         mode="book.titlepage.recto.auto.mode" 
                         select="title"/>
                </xsl:when>
              </xsl:choose>
            </fo:block>
          </fo:table-cell>
        </fo:table-row>
        <fo:table-row>
          <fo:table-cell>
            <fo:block>
              <xsl:apply-templates 
                     mode="book.titlepage.recto.mode" 
                     select="bookinfo/corpauthor"/>
            </fo:block>
          </fo:table-cell>
          <fo:table-cell>
            <fo:block>
              <xsl:apply-templates 
                     mode="book.titlepage.recto.mode" 
                     select="bookinfo/edition"/>
            </fo:block>
          </fo:table-cell> 
        </fo:table-row >  
      </fo:table-body> 
    </fo:table>
  </fo:block>
</xsl:template>

</xsl:stylesheet>
